library(Seurat)
library(scCustomize)
library(ggplot2)
library(dplyr)
library(viridis)
# library(SeuratData)
library(magrittr)
library(patchwork)
library(Signac)
# library(qs)
library(clusterProfiler)
library(msigdbr)
library(enrichplot)
library(RColorBrewer)
library(BSgenome.Hsapiens.UCSC.hg38)
library(GenomeInfoDb)
library(plyranges)
library(GenomicRanges)
library(EnsDb.Hsapiens.v86)
library(SeuratDisk)
library(SeuratObject)
library(reshape2)
library(eulerr)
library(org.Hs.eg.db)
library(BiocParallel)
library(JASPAR2022)
library(TFBSTools)

vehicle_treated <- readRDS("../working_data/vehicle_reclustered.rds")

register(SerialParam()) # calibrate parallelization
vehicle_treated2 <- RunChromVAR(vehicle_treated, genome = BSgenome.Hsapiens.UCSC.hg38, new.assay.name = "chromVAR")

saveRDS(vehicle_treated2, "../working_data/vehicle_chrom_test.rds")