---
title: "atac_cnr_cov_plots"
output: html_document
---

```{r, message=FALSE}
library(Seurat)
library(Signac)
library(dplyr)
library(ChIPpeakAnno)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ggplot2)
library(EnsDb.Hsapiens.v86)
library(plyranges)
```


```{r, warning=FALSE}
# load data in
CHLA10 <- readRDS("../working_data/CHLA10_linked.rds")
fli1_macs2_r1 <- toGRanges("../../../ewrenn/cutandrun_results_250827/04_reporting/igv/veh_FLI1_R1.macs2.peaks.cut.bed")
fli1_macs2_r2 <- toGRanges("../../../ewrenn/cutandrun_results_250827/04_reporting/igv/veh_FLI1_R2.macs2.peaks.cut.bed")
fli1_pks <- findOverlapsOfPeaks(fli1_macs2_r1, fli1_macs2_r2) # overlap fli1 peak technical replicates
# other TFs
smad2_macs2_r1 <- toGRanges("../../../ewrenn/cutandrun_results_250827/04_reporting/igv/TGFB_SMAD2_R1.macs2.peaks.cut.bed")
smad2_macs2_r2 <- toGRanges("../../../ewrenn/cutandrun_results_250827/04_reporting/igv/TGFB_SMAD2_R2.macs2.peaks.cut.bed")
smad2_pks <- findOverlapsOfPeaks(smad2_macs2_r1, smad2_macs2_r2) 
smad4_macs2_r1 <- toGRanges("../../../ewrenn/cutandrun_results_250827/04_reporting/igv/TGFB_SMAD4_R1.macs2.peaks.cut.bed")
smad4_macs2_r2 <- toGRanges("../../../ewrenn/cutandrun_results_250827/04_reporting/igv/TGFB_SMAD4_R2.macs2.peaks.cut.bed")
smad4_pks <- findOverlapsOfPeaks(smad4_macs2_r1, smad4_macs2_r2) 
```


```{r, warning=FALSE}
# get DA peaks
DefaultAssay(CHLA10) <- "ATAC"
Idents(CHLA10) <- "condition"
da_ranges <- FindMarkers(CHLA10, ident.1 = "TGFB1", ident.2 = "vehicle")
da_ranges <- subset(da_ranges, da_ranges$p_val_adj <= 0.05)

# turn da_ranges into GRanges object
da_coords <- rownames(da_ranges)
coords_parts <- strsplit(da_coords, split = "-")
coords_df <- data.frame(
  seqnames = sapply(coords_parts, `[`, 1),
  start = as.numeric(sapply(coords_parts, `[`, 2)),
  end = as.numeric(sapply(coords_parts, `[`, 3))
)
da_pks <- as_granges(coords_df)
```


```{r}
# function to create genomic range for a gene of interest -- helpful for peak plots
goi_to_roi <- function(gene_name) {
  gene_granges <- genes(EnsDb.Hsapiens.v86, filter = GeneNameFilter(gene_name))
  if (length(gene_granges) == 0) {
    stop("Error: Gene '", gene_name, "' not found in EnsDb.Hsapiens.v86 annotations.")
  }
  gene_range_granges <- gene_granges[1]
  chr <- as.character(seqnames(gene_range_granges))
  start <- as.numeric(start(gene_range_granges))
  end <- as.numeric(end(gene_range_granges))
  gene_range_string <- paste0("chr", chr, "-", start, "-", end)
  return(gene_range_string)
}
```


```{r}
# create coverage plot with ATAC signal, C&R peaks, DA (TGFB1 vs veh) ATAC peaks
multi_cov_plot <- function(goi){
  idents.plot <- c("vehicle", "TGFB1") # idents to plot
  selectgene <- goi # pick gene/region to plot around
  
  covplot <- CoveragePlot(
    object = CHLA10,
    region = selectgene,
    peaks = FALSE,
    # features = selectgene,
    expression.assay = "RNA",
    idents = idents.plot,
    extend.upstream = 500,
    extend.downstream = 10000
    )
  
  # linkplot <- LinkPlot(
  #   object = CHLA10,
  #   region = goi_to_roi(selectgene),
  #   extend.upstream = 500,
  #   extend.downstream = 10000
  #                      )
  
  peak_plot1 <- PeakPlot(
    object = CHLA10,
    region = goi_to_roi(selectgene), # function from last block
    peaks = fli1_pks$mergedPeaks, sep = c("-","-"), 
    extend.upstream = 500,
    extend.downstream = 10000
  ) + labs(caption = "^ FLI1")
  
  peak_plot2 <- PeakPlot(
    object = CHLA10,
    region = goi_to_roi(selectgene),
    peaks = smad2_pks$mergedPeaks, sep = c("-","-"), 
    extend.upstream = 500,
    extend.downstream = 10000
  ) + labs(caption = "^ SMAD2")
  
  peak_plot3 <- PeakPlot(
    object = CHLA10,
    region = goi_to_roi(selectgene),
    peaks = smad4_pks$mergedPeaks, sep = c("-","-"), 
    extend.upstream = 500,
    extend.downstream = 10000
  ) + labs(caption = "^ SMAD4")
  
  peak_plot4 <- PeakPlot(
    object = CHLA10,
    region = goi_to_roi(selectgene),
    peaks = da_pks, sep = c("-","-"), 
    extend.upstream = 500,
    extend.downstream = 10000
  ) + labs(caption = "^ DA")
  
  plot <- CombineTracks(plotlist = list(covplot, peak_plot1, peak_plot2, peak_plot3, peak_plot4), )
  return(plot)
}
```

```{r}
multi_cov_plot("RGS5")
multi_cov_plot("ETS1")
multi_cov_plot("TGFBR2")
multi_cov_plot("TGFBI")
multi_cov_plot("NT5E")
multi_cov_plot("TNC")
multi_cov_plot("TGFB2")
multi_cov_plot("FBN1")
multi_cov_plot("LOX")

```


```{r}
# LinkPlot(CHLA10_linked, region = goi_to_roi("RGS5"))

# CoveragePlot(CHLA10, goi_to_roi("TGFB2"), annotation = TRUE, peaks = TRUE, tile = TRUE, links = TRUE, idents = c("vehicle", "TGFB1"))
```


```{r}
# sessionInfo()
```