---
title: "a673_motif_volcano"
output: html_document
---

```{r, message=FALSE}
library(Seurat)
library(Signac)
library(EnhancedVolcano)
library(dplyr)
```


```{r}
#Set figure outputs
knitr::opts_chunk$set(dpi=600,
                      echo=TRUE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(dev.args=list(bg="transparent"))
knitr::opts_chunk$set(fig.path = "/data/hps/assoc/private/ewing_beti/user/jvale8/zeb_singleCell/figs/a673_motif_enrich_",  dev = c("svglite", "png"))
```


```{r}
# read in data
A673 <- readRDS("../working_data/A673_processed.rds")
Idents(A673) <- "cell_line_cond"
DefaultAssay(A673) <- "ATAC"
```


```{r}
# calculate motif enrichment
marker_ranges <- FindMarkers(A673, ident.1 = "A673_TGFB1", ident.2 = "A673_vehicle")
significant_ranges <- rownames(marker_ranges[marker_ranges$avg_log2FC > 0 & marker_ranges$p_val_adj < 0.05, ])
motif_enrichment_sig_ranges <- FindMotifs(A673, features = significant_ranges)
grant_motifs <- dplyr::select(motif_enrichment_sig_ranges, percent.observed, percent.background, fold.enrichment, p.adjust)
rownames(grant_motifs) <- motif_enrichment_sig_ranges$motif.name
write.csv(grant_motifs, "data/A673_tgfb1_motif_enrichment.csv")
```


```{r}
# fix motif names
motif_enrichment_sig_ranges$motif.name[motif_enrichment_sig_ranges$motif.name == "Smad4"] <- "SMAD4"
motif_enrichment_sig_ranges$motif.name[motif_enrichment_sig_ranges$motif.name == "Smad2::Smad3"] <- "SMAD2::SMAD3"

```


```{r, volcanoplot}
EnhancedVolcano(motif_enrichment_sig_ranges, lab=motif_enrichment_sig_ranges$motif.name, x="fold.enrichment", y="p.adjust",
                xlab = "Fold Enrichment", 
                selectLab = c("ZEB1", "SMAD4", "JUN", "FOSL2", "EWSR1-FLI1", "SMAD2::SMAD3", "SMAD5"), 
                pCutoff = 1e-2, FCcutoff=1.5, pointSize=3, drawConnectors=TRUE, labSize=5,
                col=c("lightgray", "darkgray", "darkgray", "red"), labCol="black", labFace = "bold",
                boxedLabels = TRUE, widthConnectors=1, max.overlaps=Inf) + coord_flip() + 
  ggtitle("TF motif enrichment in TGFβ1 induced differentially \n accessible peaks - A673")

```


```{r, volcanoplot}#
EnhancedVolcano(motif_enrichment_sig_ranges, lab=motif_enrichment_sig_ranges$motif.name, x="fold.enrichment", y="p.adjust",
                xlab = "Fold Enrichment", 
                selectLab = c("ZEB1", "SMAD3", "SMAD4", "JUN", "RREB1", "FOSL2", "TEAD1", "TEAD2", "TEAD3", "TEAD4", "EWSR1-FLI1", "ETS1", "LEF1", "JUND", "JUNB", "SMAD5"), 
                pCutoff = 1e-2, FCcutoff=1.5, pointSize=3, drawConnectors=TRUE, labSize=5,
                col=c("lightgray", "darkgray", "darkgray", "red"), labCol="black", labFace = "bold",
                boxedLabels = TRUE, widthConnectors=1, max.overlaps=Inf) + coord_flip() + 
  ggtitle("TF motif enrichment in TGFB1 induced differentially \n accessible peaks - A673")

```